import './globals.css'
import { Nunito } from 'next/font/google';

const nunito = Nunito({
  weight: "700",
  subsets: ['latin'],
  variable: '--font-nunito'
});

export const metadata = {
  title: 'Minesweeper',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} font-sans`}>
        {children}
      </body>
    </html>
  )
}
